=== Hoishin/rtaij-layouts/schemas/gameList.json
{
  "$schema": "http://json-schema.org/draft-04/schema",

  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "title": {
        "type": "string"
      },
      "engTitle": {
        "type": "string"
      },
      "runner": {
        "type": "string"
      },
      "commentator": {
        "type": "string"
      },
      "category": {
        "type": "string"
      },
      "hardware": {
        "type": "string"
      },
      "pk": {
        "type": "number"
      },
      "runnerPkAry": {
        "type": "array",
        "items": {
          "type": "number"
        }
      },
      "commentatorPkAry": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    }
  }
}

=== Hoishin/rtaij-layouts/extension/default/game.json
[
  {
    "title": "風のクロノア2 ～世界が望んだ忘れもの～",
    "runner": "あぐね / はるとも",
    "commentator": "Hoishin",
    "category": "Any% Popkaless",
    "hardware": "PS2",
    "pk": 20,
    "runnerPkAry": [1,2]
  },
  {
    "title": "スプラトゥーン2",
    "runner": "hashedrice",
    "commentator": "Hoishin",
    "category": "Any%",
    "hardware": "PS2",
    "pk": 5,
    "runnerPkAry": [3]
  },
  {
    "title": "スーパーマリオ64",
    "runner": "0枚RTA研究会(メーゼ/みゅう)",
    "commentator": "",
    "category": "Any% – 2 players 1 controller",
    "hardware": "PS2",
    "pk": 1,
    "runnerPkAry": [4,5]
  },
  {
    "title": "スーパードンキーコングシリーズ１，２，３ トリロジーリレー",
    "runner": "suzuri / fis",
    "commentator": "Hoishin",
    "category": "",
    "hardware": "PS2",
    "pk": 16,
    "runnerPkAry": [6,7,8]
  },
  {
    "title": "Tetris: The Grand Master series(TGM1・2・3)",
    "runner": "KevinDDR / Aperturegrillz",
    "commentator": "Hoishin",
    "category": "",
    "hardware": "PS2",
    "pk": 10,
    "runnerPkAry": [9,10,11,12,13,14,15]
  }
]
